spring.application.name=Practice
logging.level.com.example = DEBUG

Spring.datasource.url = jdbc:mysql://localhost:3306/Ecommerce
Spring.datasource.username = root
Spring.datasource.password = Parveez

# Auto schema handling
spring.jpa.hibernate.ddl-auto=update

# Show SQL in console
spring.jpa.show-sql=true

# Format SQL (makes it readable)
spring.jpa.properties.hibernate.format_sql=true

springdoc.api-docs.path=/api-docs